name: sumo_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - sumo
  - pip
  - pip:
      - traci==1.22.0
      - numpy==1.26.4
      - torch==2.6.0
      - seaborn==0.13.2
      - codecarbon==3.0.1
